#!/usr/bin/osascript
#
# Resizing windows for a standalone laptop config -- we only
# have 1440x900 to work with.
#

# desktop 2
try
tell application "Finder"
	activate
	set the bounds of the first window to {0, 0, 1050, 800}
end tell
end try

try
tell application "MacVim"
	activate	
	set the bounds of the first window to {300, 0, 1440, 800}
end tell
end try

# desktop 3
try
tell application "Terminal"
	activate
	set the bounds of the first window to {0, 0, 1440, 800}
end tell
end try

# desktop 1
try
tell application "System Events" to tell process "Slack"
	activate
	delay 0.5
	tell window 1
		set position to {0, 0}
		set size to {1000, 800}
	end tell
end tell
end try

try
tell application "Messages"
	activate
	set the bounds of the first window to {600, 200, 1400, 750}
end tell
end try

# Resizing Chrome last, because we want that to have focus
try
tell application "Chrome"
	activate
	set the bounds of the first window to {0, 0, 1440, 800}
end tell
end try
