#!/usr/bin/osascript
#
# Resizing windows for a typical "work" configuration, which assumes a
# 2560x1440 thunderbolt display on the left and an open laptop (1440x900) on
# the right.
#

# desktop 2
try
tell application "Finder"
	activate
	set the bounds of the first window to {0, 0, 1050, 1330}
end tell
end try

try
tell application "MacVim"
	activate	
	set the bounds of the first window to {1060, 0, 2550, 1330}
end tell
end try

# desktop 3
try
tell application "Terminal"
	activate
	set the bounds of the first window to {0, 0, 2550, 1330}
end tell
end try

# desktop 1
try
tell application "GitHub"
	activate
	set the bounds of the first window to {0, 0, 950, 940}
end tell
end try

# Hipchat is really weird; it seems the most finnicky of all
# the apps here. This code seems to work the "best" of any
# method I've tried, and even then, it only sometimes works.
try
tell application "System Events" to tell process "HipChat"
	activate
	tell window 1
		set position to {2570, 0}
		set size to {1100, 800}
	end tell
end tell
end try

try
tell application "Messages"
	activate
	set the bounds of the first window to {3000, 200, 3990, 890}
end tell
end try

# Resizing Chrome last, because we want that to have focus
try
tell application "Chrome"
	activate
	set the bounds of the first window to {960, 0, 2550, 1330}
end tell
end try
